name: MuleSoft Deployment

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: ${{ startsWith(github.ref, 'refs/tags/') && 'PRODUCTION' || 'SANDBOX' }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install CLI
        run: npm install -g anypoint-cli-v4

      - name: Configure Environment
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "ENVIRONMENT=PRODUCTION" >> $GITHUB_ENV
            echo "CONFIG_FILE=anypoint-info/PRODUCTION.json" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=SANDBOX" >> $GITHUB_ENV
            echo "CONFIG_FILE=anypoint-info/SANDBOX.json" >> $GITHUB_ENV
          fi

      - name: Login
        run: |
          anypoint-cli-v4 account:environment:list \
            --client_id "${{ secrets.CONNECTED_APP_ID }}" \
            --client_secret "${{ secrets.CONNECTED_APP_SECRET }}"

      - name: Create API Manager Instance
        run: |

          ASSET_ID=$(jq -r '.exchangeApi.assetId' "$CONFIG_FILE")
          ASSET_VERSION=$(jq -r '.exchangeApi.version' "$CONFIG_FILE")
          API_VERSION=$(jq -r '.exchangeApi.apiVersion' "$CONFIG_FILE")

          ARTIFACT_ID=$(mvn help:evaluate \
            -Dexpression=project.artifactId \
            -q \
            -DforceStdout)

          INSTANCE_TEMPLATE=$(jq -r '.apiManager.instanceLabelTemplate' "$CONFIG_FILE")

          INSTANCE_LABEL=${INSTANCE_TEMPLATE//\$\{ENV\}/$ENVIRONMENT}
          INSTANCE_LABEL=${INSTANCE_LABEL//\$\{APP_NAME\}/$ARTIFACT_ID}
          INSTANCE_LABEL=${INSTANCE_LABEL//\$\{API_VERSION\}/$API_VERSION}

          echo "Searching API Instance..."

          API_INSTANCE_ID=$(anypoint-cli-v4 api-mgr:api:list \
            --output json \
            | jq -r ".[] | select(.assetId==\"$ASSET_ID\") | .id" \
            | head -1)

          if [ -z "$API_INSTANCE_ID" ]; then

            echo "Creating API Manager Instance..."

            anypoint-cli-v4 api-mgr:api:manage \
              "$ASSET_ID" \
              "$ASSET_VERSION" \
              --muleVersion4OrAbove \
              --apiInstanceLabel "$INSTANCE_LABEL"

            sleep 15

            API_INSTANCE_ID=$(anypoint-cli-v4 api-mgr:api:list \
              --output json \
              | jq -r ".[] | select(.assetId==\"$ASSET_ID\") | .id" \
              | head -1)

          fi

          echo "API_INSTANCE_ID=$API_INSTANCE_ID" >> $GITHUB_ENV

      - name: Apply Policies
        run: bash scripts/policies.sh

      - name: Create SLA Tier
        run: bash scripts/sla.sh

      - name: Deploy CloudHub 2.0
        run: |
          APP_NAME=$(bash -c '
            source scripts/common.sh
            generate_app_name
          ')

          REPLICAS=$(jq -r '.deployment.replicas' "$CONFIG_FILE")
          VCORES=$(jq -r '.deployment.vCores' "$CONFIG_FILE")
          TARGET=$(jq -r '.deployment.target' "$CONFIG_FILE")
          PUBLIC_URL=$(jq -r '.deployment.publicUrl' "$CONFIG_FILE")

          mvn clean deploy -DmuleDeploy \
            -DenvName=$ENVIRONMENT \
            -DapplicationName=$APP_NAME \
            -Dreplicas=$REPLICAS \
            -DvCores=$VCORES \
            -Dtarget=$TARGET \
            -DpublicUrl=$PUBLIC_URL \
            -DapiId=$API_INSTANCE_ID \
            -DconnectedAppClientId=${{ secrets.CONNECTED_APP_ID }} \
            -DconnectedAppClientSecret=${{ secrets.CONNECTED_APP_SECRET }}