name: MuleSoft Release Creation

on:
  push:
    branches:
      - main # find and replace 'main' with 'master' in this entire script, if your default branch is named 'master'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-creation:
    runs-on: ubuntu-latest
    
    environment: ${{ 'PRODUCTION' }}
    
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17

      - name: Install XML Tools
        run: sudo apt-get install -y libxml2-utils

      - name: Convert Snapshot to Release
        run: |
          echo "Replacing SNAPSHOT version with Release version in pom.xml..."
          
          mvn versions:set \
            -DremoveSnapshot=true \
            -DgenerateBackupPoms=false

          echo "Release version set successfully in pom.xml"

      - name: Read Release Version
        id: releaseVersion
        shell: bash
        run: |
          echo "Reading Release Version from pom.xml..."

          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

          # Store the version in GitHub Actions environment variable and output variable
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

          echo "Release Version : $VERSION"

      - name: Publish Mule App (Release) Artifact to Exchange
        run: |
          echo "Publishing Mule App as a Release Artifact to Exchange..."

          mvn clean deploy \
            -DskipTests \
            -s settings.xml \
            -DconnectedAppClientId="${{ secrets.CONNECTED_APP_ID }}" \
            -DconnectedAppClientSecret="${{ secrets.CONNECTED_APP_SECRET }}"

          echo "Mule App (Release) Artifact published successfully"
      
      - name: Create Git Tag
        shell: bash
        run: |
          echo "Creating Git Tag for Release Version..."

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "v${VERSION}"
          git push origin "v${VERSION}"

          echo "Git Tag v${VERSION} created and pushed successfully"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo "Creating GitHub Release for v${VERSION}..."

          gh release create "v${VERSION}" \
            target/*.jar \
            --title "Release v${VERSION}" \
            --generate-notes
            
          echo "GitHub Release for v${VERSION} created successfully"

      - name: Increment to Next Snapshot
        run: |
          echo "Incrementing to Next Snapshot Version..."

          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

          VERSION=${VERSION%-SNAPSHOT}

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          PATCH=$((PATCH + 1))

          NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}-SNAPSHOT"

          mvn versions:set \
            -DnewVersion="$NEXT_VERSION" \
            -DgenerateBackupPoms=false

          echo "Next Snapshot Version set to $NEXT_VERSION in pom.xml"

      - name: Commit Next Snapshot
        shell: bash
        run: |
          echo "Committing Next Snapshot Version..."

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add pom.xml

          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi

          git commit -m "Prepare next development iteration"
          git push

          echo "Next Snapshot Version committed and pushed successfully"

      - name: Create Sync PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking for existing open Sync PR from main to develop..."

          EXISTING_PR=$(gh pr list \
            --base develop \
            --head main \
            --state open \
            --json number \
            --jq 'length')

          if [ "$EXISTING_PR" -eq 0 ]; then

            echo "Not found"
            echo "Creating a new Sync PR..."

            gh pr create \
              --base develop \
              --head main \
              --title "sync w/ main" \
              --body "Automatically created after release"
                
            echo "Sync PR created successfully"
          
          else
          
            echo "An open sync PR already exists"
            echo "Skipping creation..."
          
          fi
