name: Security Scan

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint GitHub Actions workflows
        uses: raven-actions/actionlint@v2

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
