name: Security Scan

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh \
            | sh -s -- -b /usr/local/bin
      
      - name: Scan full Git history
        run: |
          gitleaks git --log-opts="--all" --verbose
