name: Security Scan

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Gitleaks & Scan
        run: |
          git clone https://github.com/gitleaks/gitleaks.git
          cd gitleaks
          make build
          gitleaks git \
            --log-opts="--all" \
            --verbose \
            --redact \
            --report-format sarif \
            --report-path results.sarif
